server:
  port: 20080

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:buyright;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username:
    password:
  jpa:
    open-in-view: false
    show-sql: true
    hibernate.ddl-auto: create-drop

logging:
  level:
    org:
      springframework:
        data: DEBUG

