server:
  port: 20080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/uc?useUnicode=true&amp;characterEncoding=utf8&amp;allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  jpa:
    show-sql: true
    hibernate.ddl-auto: update

